[package]
name = "pineappl"
version = "0.3.0"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/N3PDF/pineappl"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "PineAPPL is not an extension of APPLgrid"

[dependencies]
anyhow = "1.0"
arrayvec = "0.5"
bincode = "1.0"
either = "1.6"
enum_dispatch = "0.3"
float-cmp = "0.8"
itertools = "0.9"
lz-fear = "0.1"
ndarray = { features = ["serde"], version = "0.13.1" }
pyo3 = { features = ["extension-module"], optional = true, version = "0.12.4" }
rustc-hash = "1.1.0"
serde = { features = ["derive"], version = "1.0" }
thiserror = "1.0"

[lib]
name = "pineappl"
crate-type = ["cdylib", "lib"]

[features]
python = ["pyo3"]

[dev-dependencies]
lhapdf = "0.1.8"
rand = { default-features = false, version = "0.7" }
rand_pcg = { default-features = false, version = "0.2" }
yaml-rust = "0.4"

[[example]]
name = "import-yadism-yaml"
