[package]
name = "pineappl"
version = "0.1.0"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/N3PDF/pineappl"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "PineAPPL is not an extension of APPLgrid"

[dependencies]
serde = { features = ["derive"], version = "1.0" }
typetag = "0.1"

[dev-dependencies]
#bincode = "1.0"
num-complex = "0.2"
rand = "0.7"
rand_pcg = "0.2"
