[package]
name = "pineappl_cli"
version = "0.3.0"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/N3PDF/pineappl"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "Read, write, and query PineAPPL grids"

[dependencies]
clap = { default-features = false, features = ["suggestions"], version = "~2.33.0" }
itertools = "0.9"
lhapdf = "0.1.9"
num_cpus = "1.0"
pineappl = { path = "../pineappl", version = "0.3" }
prettytable-rs = "^0.8"
rayon = "1.3"

[[bin]]
name = "pineappl"
path = "src/main.rs"

[package.metadata.docs.rs]
rustc-args = [ "--cfg feature=\"docs-only\"" ]
