[package]
name = "pineappl_capi"
version = "0.1.0"
authors = ["Christopher Schwan <handgranaten-herbert@posteo.de>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/N3PDF/pineappl"
readme = "README.md"
keywords = ["high-energy-physics", "physics"]
categories = ["science"]
description = "C language interface to PineAPPL"

[lib]
crate-type = ["cdylib"]
name = "pineappl"

[dependencies]
pineappl_core = { path = "../pineappl_core", version = "0.1.0" }
bincode = "1.0"
