language = "C"

############## Options for Wrapping the Contents of the Header #################

include_guard = "PINEAPPL_H"
include_version = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
no_includes = true
cpp_compat = true
usize_is_size_t = true

############################## Codegen Options ##################################

[export.rename]
"Grid" = "pineappl_grid"
"Lumi" = "pineappl_lumi"
"KeyVal" = "pineappl_keyval"
"SubGrid" = "pineappl_subgrid"

############## Options for How Your Rust library Should Be Parsed ##############

[parse]
parse_deps = true
include = ["pineappl"]
