name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install LHAPDF 6.3.0
      run: |
        wget 'https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.3.0.tar.gz' -O LHAPDF-6.3.0.tar.gz
        tar xzf LHAPDF-6.3.0.tar.gz
        cd LHAPDF-6.3.0
        ./configure --prefix=${HOME}/prefix
        make -j
        make install
        echo "::add-path::${HOME}/prefix/bin"
        echo "::set-env name=LD_LIBRARY_PATH::${HOME}/prefix/lib"
        echo "::set-env name=PKG_CONFIG_PATH::${HOME}/prefix/lib/pkgconfig"
        echo "::set-env name=PYTHONPATH::${HOME}/prefix/lib/python3.7/site-packages"
    - name: Install NNPDF31_nlo_as_0118_luxqed
      run: |
        lhapdf install NNPDF31_nlo_as_0118_luxqed
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose
    - name: Generate doctest coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --workspace --exclude pineappl_cli --exclude pineappl_capi --ignore-tests
        run-types: Doctests,Tests
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: Install cargo-c
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-c
    - name: Install PineAPPL's C API
      run: |
        ls -alR $HOME/prefix
        cargo cinstall -vv --prefix=$HOME/prefix --manifest-path pineappl_capi/Cargo.toml
    - name: Test C++ example
      run: |
        cd examples/capi-dy-aa
        make
        ./dyaa
        cd ../../
    - name: Install Python wrapper
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        cd wrappers/python
        pip install .
        pylint src -E -d E1123,E1120
    - name: Test with pytest
      run: |
        pytest --pyargs pineappl
