name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install LHAPDF 6.3.0
      run: |
        wget 'https://lhapdf.hepforge.org/downloads/?f=LHAPDF-6.3.0.tar.gz' -O LHAPDF-6.3.0.tar.gz
        tar xzf LHAPDF-6.3.0.tar.gz
        cd LHAPDF-6.3.0
        ./configure --prefix=/usr
        make -j
        sudo make install
    - name: Install NNPDF31_nlo_as_0118_luxqed
      run: |
        sudo python3.7 /usr/bin/lhapdf install NNPDF31_nlo_as_0118_luxqed
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --workspace --exclude pineappl_cli --exclude pineappl_capi
        run-types: Doctests,Tests
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
